### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/xtext/xbase/lib/CollectionLiterals when using layered when upgrading from 0.10 to 0.11

### ISSUE THREAD

**Issue by jbarrez** [eclipse/elk#1176]
I'm using org.eclipse.elk.core and org.eclipse.elk.alg.layered as maven dependencies.

After upgrading to 0.11, I'm getting
java.lang.NoClassDefFoundError: org/eclipse/xtext/xbase/lib/CollectionLiterals

Which is caused by an import org.eclipse.elk.alg.layered.options.LayeredMetaDataProvider

Is this a bug (wrongly added import) or do I need to have a new additional dependency on the package that contains the CollectionLiterals class?
